# This is the network config written by 'subiquity'
network:
  ethernets:
    ens18:
      dhcp4: false
      addresses:
        - "{{ ipv4_private }}/24"
      nameservers:
        addresses: [192.168.1.27]
      routes:
        - to: default
          via: 192.168.1.1
  version: 2
