---
 - name: "SET DNS ON CONSUL AND NOMAD SERVERS"
   hosts: nomad:consul
   become: yes
   remote_user: minion
   become_user: root
   gather_facts: true
   tasks:

    - name: disable systemd resolved
      systemd:
        state: stopped
        enabled: false
        name: systemd-resolved

    - name: Remove systemd resolv.conf remains
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
        owner: root
        group: root

    - name: Ensure /etc/resolv.conf is present and is a file
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: touch
        owner: root
        group: root

    - name: set pihole as default dns
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 192.168.1.27"
        state: present
